#### NOTICE: THIS FILE IS AUTOGENERATED
#### MODIFICATIONS MAY BE LOST IF DONE IMPROPERLY
#### PLEASE SEE THE ONLINE DOCUMENTATION FOR EXAMPLES

from swgpy.object import *
from . import base

class Template(BaseTemplate):
	name = "object/weapon/melee/knife/shared_knife_survival.iff"
	is_prototype = False
	
	def create(self, kernel, params):
		result = Weapon()		
		Template.init(kernel, params, result)
		
		return result
	
	@staticmethod
	def init(kernel, params, result):
		try:
			base.init(kernel, params, result)
		except AttributeError:
			print('base.init doesnt exist')
		result.template = "object/weapon/melee/knife/shared_knife_survival.iff"
		result.attribute_template_id = 10
		result.stfName("weapon_name","knife_survival")	
		
		#### BEGIN MODIFICATIONS ####		
		result.setStringAttribute('wpn_armor_pierce_rating', 'None')
		result.setFloatAttribute('wpn_attack_speed', 4.5)
		result.setStringAttribute('cat_wpn_damage.wpn_damage_type', 'Kinetic')
		result.setIntAttribute('cat_wpn_damage.wpn_damage_min', 14)
		result.setIntAttribute('cat_wpn_damage.wpn_damage_max', 28)
		result.setFloatAttribute('cat_wpn_damage.wpn_wound_chance', 5.0)
		result.setIntAttribute('cat_wpn_rangemods.wpn_range_zero', 0)
		result.setIntAttribute('cat_wpn_rangemods.wpn_range_mid', 3)
		result.setIntAttribute('cat_wpn_rangemods.wpn_range_max', 4)
		result.setIntAttribute('cat_wpn_attack_cost.wpn_attack_cost_health', 9)
		result.setIntAttribute('cat_wpn_attack_cost.wpn_attack_cost_action', 28)
		result.setIntAttribute('cat_wpn_attack_cost.wpn_attack_cost_mind', 6)	
		####  END MODIFICATIONS  ####
		
def loadTemplates(addTemplate):
	addTemplate(Template())